# Generated by Django 3.0.2 on 2020-01-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='course',
            new_name='courses',
        ),
    ]
